'use strict';
/** Build a per-language VSIX (language pack extension) from locales/<lang>/strings.json. */
const fs = require('fs');
const path = require('path');
const { zipStore } = require('./zip');
const { expandToPackFormat } = require('./nls');

const PUBLISHER = 'agy-i18n';

function extensionId(lang) {
  return `${PUBLISHER}.antigravity-language-pack-${lang}`;
}

function buildVsix({ repoRoot, lang, meta, outDir, version, ideInfo }) {
  const stringsFile = path.join(repoRoot, 'locales', lang, 'strings.json');
  const flat = JSON.parse(fs.readFileSync(stringsFile, 'utf8'));
  const translated = Object.values(flat).filter((v) => typeof v === 'string' && v.trim()).length;

  const contents = expandToPackFormat(flat);
  const mainI18n = {
    '': [
      'Community translations for Google Antigravity — https://github.com/HNUYJJ/antigravity-i18n',
      'Licensed under the MIT License. Generated by antigravity-i18n; do not edit by hand.',
    ],
    version: '1.0.0',
    contents,
  };

  const pkg = {
    name: `antigravity-language-pack-${lang}`,
    displayName: `Antigravity Language Pack · ${meta.localizedLanguageName}`,
    description: `Community ${meta.languageName} translations for Google Antigravity-specific UI (Agent panel, welcome, model management…). Install an official VS Code ${meta.languageName} Language Pack alongside for the base editor UI.`,
    version,
    publisher: PUBLISHER,
    license: 'MIT',
    repository: { type: 'git', url: 'https://github.com/HNUYJJ/antigravity-i18n' },
    bugs: { url: 'https://github.com/HNUYJJ/antigravity-i18n/issues' },
    markdown: 'github',
    qna: false,
    engines: { vscode: '*' },
    categories: ['Language Packs'],
    keywords: [meta.nativeName],
    contributes: {
      localizations: [
        {
          languageId: meta.languageId,
          languageName: meta.languageName,
          localizedLanguageName: meta.localizedLanguageName,
          translations: [{ id: 'vscode', path: './translations/main.i18n.json' }],
        },
      ],
    },
  };

  const readme = [
    `# Antigravity Language Pack · ${meta.localizedLanguageName}`,
    '',
    `Community ${meta.languageName} translations for **Google Antigravity**-specific UI strings`,
    `(${translated} strings, built for Antigravity IDE ${ideInfo.ideVersion || ideInfo.version}).`,
    '',
    'Part of the [antigravity-i18n](https://github.com/HNUYJJ/antigravity-i18n) project.',
    '',
    '## Usage',
    '',
    '1. Install the official VS Code ' + meta.languageName + ' Language Pack for the base editor UI.',
    '2. Install this pack.',
    '3. `Ctrl/Cmd+Shift+P` → **Configure Display Language** → ' + meta.localizedLanguageName + ' → restart.',
    '',
    'MIT © antigravity-i18n contributors. Not affiliated with or endorsed by Google.',
  ].join('\n');

  const manifest = `<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="antigravity-language-pack-${lang}" Version="${version}" Publisher="${PUBLISHER}"/>
    <DisplayName>Antigravity Language Pack · ${meta.localizedLanguageName}</DisplayName>
    <Description xml:space="preserve">Community ${meta.languageName} translations for Google Antigravity-specific UI. Pair with the official VS Code ${meta.languageName} Language Pack for the base editor.</Description>
    <Categories>Language Packs</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Code.Engine" Value="*"/>
      <Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value=""/>
      <Property Id="Microsoft.VisualStudio.Code.ExtensionPack" Value=""/>
      <Property Id="Microsoft.VisualStudio.Code.ExtensionKind" Value="ui,workspace"/>
      <Property Id="Microsoft.VisualStudio.Code.LocalizedLanguages" Value="${meta.languageId}"/>
    </Properties>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code"/>
  </Installation>
  <Dependencies/>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true"/>
  </Assets>
</PackageManifest>
`;

  const contentTypes = `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json"/>
  <Default Extension="xml" ContentType="text/xml"/>
  <Default Extension="md" ContentType="text/markdown"/>
  <Default Extension="txt" ContentType="text/plain"/>
</Types>
`;

  const license = fs.readFileSync(path.join(repoRoot, 'LICENSE'), 'utf8');

  const vsix = zipStore([
    { name: 'extension.vsixmanifest', data: manifest },
    { name: '[Content_Types].xml', data: contentTypes },
    { name: 'extension/package.json', data: JSON.stringify(pkg, null, '\t') },
    { name: 'extension/translations/main.i18n.json', data: JSON.stringify(mainI18n, null, '\t') },
    { name: 'extension/README.md', data: readme },
    { name: 'extension/LICENSE.txt', data: license },
  ]);

  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `antigravity-language-pack-${lang}-${version}-agy${ideInfo.ideVersion || ideInfo.version}.vsix`);
  fs.writeFileSync(outFile, vsix);
  return { outFile, translated, modules: Object.keys(contents).length };
}

module.exports = { buildVsix, extensionId, PUBLISHER };
